### ISSUE TITLE
smtp_tls: better fix

### ISSUE THREAD

**Issue by yn** [collectiveidea/action_mailer_optional_tls#1]
As your comment indicates, the fix only works under rails, because Kernel::VERSION isn't available in ruby w.o. rails.

However, Object::RUBY_VERSION is available in standard ruby, and is equal to the same value

**Comment by bkeepers** [comment]
Use VERSION instead of Kernel::VERSION. Closed by 08237479f2d85f9f7e664b61e509b9c23b6dc6cc

**Comment by dohkoos** [comment]
ruby 1.9 does not support constant VERSION. I got the following error
uninitialized constant Net::SMTP::VERSION

I changed VERSION to RUBY_VERSION, it's ok.

**Comment by yn** [comment]
I thought Ruby 1.9 doesn't need this plugin because it supports GMail TLS out of the box?
